"""Tests for the Scherneck BLQ reader and ocean-tide-loading displacement."""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path

import numpy as np
import pytest

from rinexpy.geodesy import lla_to_ecef
from rinexpy.otl import (
    ocean_tide_loading_displacement,
    ocean_tide_loading_ecef,
    read_blq,
)


# A representative synthetic BLQ entry shaped like the Onsala output for
# a real coastal site (Oslo, NO). The amplitudes / phases are realistic-
# scale but not the exact Onsala numbers (which depend on a continually
# updated ocean tide model).
SAMPLE_BLQ = """\
$$ Ocean loading displacement
$$ Generated by HARDISP test suite
$$
$$ OSLO
$$ Site coordinates: 59.91N 10.75E, 50 m
$$
  .00345 .00125 .00046 .00037 .00133 .00135 .00043 .00026 .00010 .00005 .00003
  .00135 .00056 .00020 .00014 .00078 .00068 .00024 .00017 .00007 .00004 .00002
  .00079 .00029 .00009 .00012 .00103 .00073 .00020 .00015 .00007 .00004 .00002
  -73.4  -45.1 -103.7  -45.1   -2.6  -22.6   -9.5  -68.4  -57.0    1.5   38.7
  147.0  151.8  108.2  151.8 -114.5 -141.5 -169.8 -126.5  130.6  176.9    1.8
   16.5   16.3   30.0   16.3  -41.5  -54.4  -54.4  -54.4 -150.6 -176.5  -77.0
"""


@pytest.fixture
def blq_file(tmp_path: Path) -> Path:
    p = tmp_path / "oslo.blq"
    p.write_text(SAMPLE_BLQ)
    return p


def test_read_blq_returns_one_station(blq_file: Path):
    stations = read_blq(blq_file)
    assert "OSLO" in stations
    e = stations["OSLO"]
    for k in ("amp_radial", "amp_west", "amp_south",
              "phase_radial", "phase_west", "phase_south"):
        assert e[k].shape == (11,)


def test_read_blq_first_constituent_is_m2(blq_file: Path):
    """The first amplitude entry corresponds to M2; it's the largest in
    a coastal BLQ block (~3-5 mm vs sub-mm for the lesser constituents)."""
    e = read_blq(blq_file)["OSLO"]
    assert e["amp_radial"][0] == pytest.approx(0.00345)
    assert e["phase_radial"][0] == pytest.approx(-73.4)


def test_read_blq_rejects_empty(tmp_path: Path):
    p = tmp_path / "empty.blq"
    p.write_text("# nothing here\n")
    with pytest.raises(ValueError, match="no station blocks"):
        read_blq(p)


def test_otl_displacement_amplitude_in_centimeter_band(blq_file: Path):
    """For the sample BLQ entry, peak radial amplitude across a day is
    a few mm (slightly less than sum of M2+S2+K2 radials ~ 5 mm)."""
    e = read_blq(blq_file)["OSLO"]
    mags = []
    for hour in range(0, 24):
        epoch = datetime(2024, 6, 21, hour, 0, 0, tzinfo=timezone.utc)
        d = ocean_tide_loading_displacement(e, epoch)
        mags.append(np.linalg.norm(d))
    peak = max(mags)
    # Should be a few millimeters; well under 2 cm.
    assert 0.5e-3 < peak < 0.02, f"peak {peak:.4f} m outside the expected band"


def test_otl_returns_zero_with_zero_amplitudes(blq_file: Path):
    e = read_blq(blq_file)["OSLO"]
    e2 = {k: np.zeros_like(v) for k, v in e.items()}
    epoch = datetime(2024, 6, 21, 12, 0, 0, tzinfo=timezone.utc)
    d = ocean_tide_loading_displacement(e2, epoch)
    np.testing.assert_array_equal(d, np.zeros(3))


def test_otl_enu_to_ecef_shape(blq_file: Path):
    e = read_blq(blq_file)["OSLO"]
    station = np.array(lla_to_ecef(59.91, 10.75, 50.0))   # Oslo-ish
    epoch = datetime(2024, 6, 21, 12, 0, 0, tzinfo=timezone.utc)
    d_ecef = ocean_tide_loading_ecef(e, station, epoch)
    assert d_ecef.shape == (3,)
    # Magnitude in ECEF matches the ENU magnitude (no scaling lost).
    d_enu = ocean_tide_loading_displacement(e, epoch)
    np.testing.assert_allclose(
        np.linalg.norm(d_ecef), np.linalg.norm(d_enu), rtol=1e-6
    )
